### ISSUE TITLE
Change url paths to relative paths in packages

### ISSUE THREAD

**Issue by aivashyna** [PayU-EMEA/PayU-Flutter#16]
For ex:

**from:**
```yaml
payu_about: 
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_about
```

**to:** 
```yaml
payu_about:
  ../payu_about
```
